### ISSUE TITLE
Multiple Windows Crashes on API 24+

### ISSUE THREAD

**Issue by rayliverified** [diegoRodriguezAguila/FloatingWindows#2]
*On Android Nougat and up devices, creating multiple windows crashes with window instance already added error.

**Comment by diegoRodriguezAguila** [comment]
Hello, i don't see why it couldn't be compatible, even though, when working on API > 23 you do need to ask for a special permission so the app doesn't crash, that permission is to draw over applications.

**Comment by rayliverified** [comment]
I don't think that's the problem. I did grant the "Draw over other apps" permission but it crashes if you attempt to open more than 1 window.

**Comment by rayliverified** [comment]
Closing for now.
