### ISSUE TITLE
error "nulltoken, is your activity running?" on android Oreo

### ISSUE THREAD

**Issue by Asykur** [diegoRodriguezAguila/FloatingWindows#3]
is this library allready support for android Oreo?

**Comment by diegoRodriguezAguila** [comment]
Hello, i don't see why it couldn't be compatible, even though, when working on API > 23 you do need to ask for a special permission so the app doesn't crash, that permission is to draw over applications.

**Comment by Asykur** [comment]
i allready change method inside FloatingWindowViewHolder class and its work for OREO, you should update your library ..

mParams = new WindowManager.LayoutParams( WindowManager.LayoutParams.WRAP_CONTENT, WindowManager.LayoutParams.WRAP_CONTENT,
                    WindowManager.LayoutParams.TYPE_APPLICATION_OVERLAY, WindowManager.LayoutParams.FLAG_NOT_FOCUSABLE, PixelFormat.TRANSLUCENT);
